### ISSUE TITLE
Support for managed identities

### ISSUE THREAD

**Issue by anth12** [StefH/DistributedCache.AzureTableStorage#15]
Any plans to support table storage auth via managed identities to avoid connection strings?

Perhaps an overload on the DI to allow a table client would be simplest with the connection established on the consumer code.

**Comment by StefH** [comment]
@anth12 
This is indeed possible. I did build this some time ago for another project.

I'll see if this can be added to this project.

When there is a new preview version, are you able to test this?

**Comment by anth12** [comment]
Thanks! Yes I'd happily test

**Comment by StefH** [comment]
@anth12 
Can you try `DistributedCache.AzureTableStorage.3.1.0-preview-01` ?

**Comment by StefH** [comment]
https://github.com/StefH/DistributedCache.AzureTableStorage/pull/16

**Comment by anth12** [comment]
Thanks @StefH, that was very quick. I've added a comment to the PR regarding the ConnectionString null guard.

Otherwise, it worked perfectly fine locally with an AD account and ran on Azure with a system-generated identity.

**Comment by StefH** [comment]
@anth12 
A last double check : can you test `preview-01`?

**Comment by anth12** [comment]
Yes, `3.1.0-preview-02`  is working with just `StorageAccountUri` locally & on an Azure App Service.

Thanks again for adding support so quickly.
