### ISSUE TITLE
Expose TableClientOptions.ServiceVersion?

### ISSUE THREAD

**Issue by natiox** [StefH/DistributedCache.AzureTableStorage#17]
We tried to use V3 of this package in Azure Stack Hub (an on-premise version of Azure that uses an older version of the Azure Storage API).  We looked for a way to set up the AzureServiceClient creation with a non-default TableClientOptions.ServiceVersion, but couldn't seem to find any.  Would it be possible to expose a version to be sent on [this ](https://github.com/StefH/DistributedCache.AzureTableStorage/blob/a18de2367f501046c6688f11e6d11d2ddc2ee6d7/src/DistributedCache.AzureTableStorage.V3/Implementations/TableStorageClientUsingStorageConnectionString.cs#L11)constructor call?

On the other hand, I imagine the use case to set the version is rare so perhaps not worth considering.

**Comment by StefH** [comment]
@natiox 
According to this page (https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableserviceclient?view=azure-dotnet) there is no constructor which allows setting the version?

Also for TableClientOptions, I cannot find a property named ServiceVersion?

**Comment by natiox** [comment]
It would be through [this ](https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableserviceclient.-ctor?view=azure-dotnet#azure-data-tables-tableserviceclient-ctor(system-string-azure-data-tables-tableclientoptions))TableServiceClient constructor, using [this ](https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclientoptions.-ctor?view=azure-dotnet#azure-data-tables-tableclientoptions-ctor(azure-data-tables-tableclientoptions-serviceversion))constructor on the TableClientOptions.

**Comment by StefH** [comment]
Ah I see.

Two enum values are possible https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclientoptions.serviceversion?view=azure-dotnet

<html><body>


V2019_02_02 | 1 | The Tables API version 2019-02-02.
-- | -- | --
V2020_12_06 | 2 | The Tables API version 2020-12-06.


</body>
</html>


---


You can make a PR for this to add a nullable int or nullable string for the version to this options class:
https://github.com/StefH/DistributedCache.AzureTableStorage/blob/master/src/DistributedCache.AzureTableStorage/Options/AzureTableStorageCacheOptions.cs

And then in case this has a value, use the special constructor, else keep the original logic.
