### ISSUE TITLE
Cache cleanup

### ISSUE THREAD

**Issue by elvirdolic** [StefH/DistributedCache.AzureTableStorage#4]
Is there a way to clean up the cache on startup? Means all expired caches will be deleted again on table storage?

**Comment by StefH** [comment]
This is not yet implemented. Would this be useful?

**Comment by elvirdolic** [comment]
Would make sense SqlServer Dist Cache is deleting expired items

**Comment by StefH** [comment]
@elvirdolic Can you please try preview version https://www.nuget.org/packages/DistributedCache.AzureTableStorage/2.0.0-preview-01 which support cleanup, just like SqlServer Dist Cache.

**Comment by StefH** [comment]
@elvirdolic Did you have time to validate this preview version?

**Comment by elvirdolic** [comment]
Im really sorry we have decided against table storage cache as our data is bigger then max allowed columnsize.

**Comment by StefH** [comment]
OK, no problem.

@lucax88x : since you were also involved in this project by adding an issue, maybe you can also double check if this new functionality works correct?

**Comment by lucax88x** [comment]
Sure, how I can test this? Need to create a cached stuff which expires in 10 mins and check if it expires in startup?

**Comment by StefH** [comment]
Yes. Correct.
1. Add some items with 10 mins expire
2. Wait 11 mins
3. Start again
4. Items should be removed automatically

**Comment by StefH** [comment]
@lucax88x Did you have time to test this?

**Comment by lucax88x** [comment]
@StefH sorry man, I will test on Monday.

**Comment by lucax88x** [comment]
@StefH Looks like it's not deleting, do I need to call something on startup?

**Comment by lucax88x** [comment]
@StefH  I tried to put 5 mins cache, but it didn't delete it on startup, do I need to call something specific?

**Comment by StefH** [comment]
Did you try this version `https://www.nuget.org/packages/DistributedCache.AzureTableStorage/2.0.0-preview-01` ?

**Comment by lucax88x** [comment]
Yes, this was the one I had already installed, didn't need to change.

If it does matter, I'm working on Azure Functions.

**Comment by StefH** [comment]
Ah I see, I'm very sorry.

I've created preview-02, this should be available on NuGet within some time.

**Comment by StefH** [comment]
@lucax88x Did you have time to test?

**Comment by StefH** [comment]
@lucax88x and @lucax88x 

This functionality will be in the `1.1.0` release.
However the WindowsAzure.Storage dependency is declared deprecated by Microsoft.

So I also created a new 2.0.0 version which uses Microsoft.Azure.Cosmos.Table/2.0.0-preview

**Comment by StefH** [comment]
https://github.com/StefH/DistributedCache.AzureTableStorage/pull/7
