### ISSUE TITLE
Cache Table must be created manually

### ISSUE THREAD

**Issue by lucax88x** [StefH/DistributedCache.AzureTableStorage#5]
Hello :)

Thanks for the project.

I've been trying this in the last 30 mins, but I was keeping getting 404 from the PUT to Table Storage.

I had to download your source code to understand that I had to manually create the Table in order to make it works.

I'm not using Azure Table Storage for now, but emulating them with Azurite V2, so this could be the problem.. 

At least in the future, if someone has the same issue he knows how to fix it.

**Comment by StefH** [comment]
@lucax88x Can you please try preview version https://www.nuget.org/packages/DistributedCache.AzureTableStorage/2.0.0-preview-01 which will default create the table if not-existing, unless the option is set to false.

**Comment by lucax88x** [comment]
I'll try it out on monday on office ;)

**Comment by StefH** [comment]
Hello @lucax88x , did you have time to verify that new version?

**Comment by lucax88x** [comment]
@StefH  Nope, I've been sick, I'm gonna try it right now. sorry.

**Comment by StefH** [comment]
_I've been sick_ I hope nothing serious?

**Comment by lucax88x** [comment]
Eheh, thanks for your thoughts, just a bad flu, the problem is that this 'flu' propagated to all family :D (and no, not the corona)

**Comment by lucax88x** [comment]
I just tried, works perfectly, thanks!
