### ISSUE TITLE
Update to latest storage SDK

### ISSUE THREAD

**Issue by tmakin** [StefH/DistributedCache.AzureTableStorage#6]
Would you consider updating the new v2.0 package to use the latest storage SDK?
i.e. `Microsoft.Azure.Storage.Table` instead of `WindowsAzure.Storage`

I don't want to introduce the legacy storage dependency into my project so sadly can't use this library in its current state.

See this SO thread for more info:
https://stackoverflow.com/a/53218759/965738

Thanks,
Tom

**Comment by StefH** [comment]
@tmakin Is this issue valid ?

**Comment by tmakin** [comment]
Sorry, I jumped the gun. I don't think `Microsoft.Azure.Storage.Table` exists. Seems it's now been merged with Cosmos Table API. I'll do a bit more homework and get back to you. However, having now pulled the project down I think it would be good to update all other dependencies to the latest net core 3 versions.

**Comment by StefH** [comment]
Other question;
If you have time, can you check https://github.com/StefH/DistributedCache.AzureTableStorage/issues/4 ? Maybe you also have some ideas on this.

**Comment by tmakin** [comment]
Cool, I'll try and take a look at #4 once I get up and running. I've been reading around storage SDK ecosystem and turns out there is a whole new set of libraries I wasn't aware of.
https://github.com/Azure/azure-sdk-for-net/tree/Azure.Storage.Blobs_12.4.4/sdk/storage

So `Microsoft.Azure.Storage` has also been deprecated. I also found a new WIP project which looks table-specific but that is not on nugget yet. https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables

Overall I would vote to close this issue and revisit in a few months when the dust settles on all the new libraries.

**Comment by StefH** [comment]
https://github.com/dtretyakov/WindowsAzure/pull/70

**Comment by StefH** [comment]
The replacement could be : https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table/2.0.0-preview

**Comment by tmakin** [comment]
Yeah, I had a play with the cosmos table version today but the API is quite different and also has a dependency on the Cosmos DB client which I don't like. It might clash with other cosmos related libraries within a given project. 

On a related note, I found a new Cosmos based cache implementation from MS which looks promising. https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos

**Comment by StefH** [comment]
Interesting!

However in my PR (https://github.com/dtretyakov/WindowsAzure/pull/70)  on the `WindowsAzure.StorageExtensions` which I use now for this project.
I just replaced `WindowsAzure.Storage` by `Microsoft.Azure.Cosmos.Table`, and this interface is 99% the same.

**Comment by StefH** [comment]
@tmakin I did release this version `2.0.0-preview-03` which should use the Microsoft.Azure.Cosmos.Table instead of the old WindowsAzure.Storage.

Can you please test ?

**Comment by tmakin** [comment]
Sorry, I've abandoned my idea of using storage table as a cache for now. I'm going to wait until MS finish reorganising things and then revisit.

**Comment by StefH** [comment]
OK Thanks for the ideas!
